//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SeleccionBDEntities : DbContext
    {
        public SeleccionBDEntities()
            : base("name=SeleccionBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Perfiles> Perfiles { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<pa_ObtenerPerfilesUsuario_Result> pa_ObtenerPerfilesUsuario(string nicknameUsuario)
        {
            var nicknameUsuarioParameter = nicknameUsuario != null ?
                new ObjectParameter("nicknameUsuario", nicknameUsuario) :
                new ObjectParameter("nicknameUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtenerPerfilesUsuario_Result>("pa_ObtenerPerfilesUsuario", nicknameUsuarioParameter);
        }
    
        public virtual ObjectResult<pa_VerificarLogin_Result> pa_VerificarLogin(string nicknameUsuario, string pass)
        {
            var nicknameUsuarioParameter = nicknameUsuario != null ?
                new ObjectParameter("nicknameUsuario", nicknameUsuario) :
                new ObjectParameter("nicknameUsuario", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_VerificarLogin_Result>("pa_VerificarLogin", nicknameUsuarioParameter, passParameter);
        }
    
        public virtual ObjectResult<pa_ObtenerNombreUsuario_Result> pa_ObtenerNombreUsuario(string nicknameUsuario)
        {
            var nicknameUsuarioParameter = nicknameUsuario != null ?
                new ObjectParameter("nicknameUsuario", nicknameUsuario) :
                new ObjectParameter("nicknameUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtenerNombreUsuario_Result>("pa_ObtenerNombreUsuario", nicknameUsuarioParameter);
        }
    
        public virtual ObjectResult<pa_ModificarPermisosPerfil_Result> pa_ModificarPermisosPerfil(string nicknameUsuario, Nullable<int> codPerfil)
        {
            var nicknameUsuarioParameter = nicknameUsuario != null ?
                new ObjectParameter("nicknameUsuario", nicknameUsuario) :
                new ObjectParameter("nicknameUsuario", typeof(string));
    
            var codPerfilParameter = codPerfil.HasValue ?
                new ObjectParameter("codPerfil", codPerfil) :
                new ObjectParameter("codPerfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ModificarPermisosPerfil_Result>("pa_ModificarPermisosPerfil", nicknameUsuarioParameter, codPerfilParameter);
        }
    }
}
