//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public Expediente()
        {
            this.PuestoPorExpediente = new HashSet<PuestoPorExpediente>();
        }
    
        public string identificacion { get; set; }
        public string promedioprueba { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correoelectronico { get; set; }
        public string genero { get; set; }
        public string estadocivil { get; set; }
        public string idioma { get; set; }
        public string certificacion { get; set; }
        public string titulo { get; set; }
        public string ubicacion { get; set; }
    
        public virtual Expediente Expediente1 { get; set; }
        public virtual Expediente Expediente2 { get; set; }
        public virtual ICollection<PuestoPorExpediente> PuestoPorExpediente { get; set; }
    }
}
