//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Expediente
    {
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public int edad { get; set; }
        public int codgenero { get; set; }
        public int codestadocivil { get; set; }
    
        public virtual EstadosCiviles EstadosCiviles { get; set; }
        public virtual Generos Generos { get; set; }
    }
}
