//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public Expediente()
        {
            this.PuestoPorExpediente = new HashSet<PuestoPorExpediente>();
        }
    
        public string identificacion { get; set; }
        public string promedioprueba { get; set; }
        public System.DateTime fechanacimiento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correoelectronico { get; set; }
        public string genero { get; set; }
        public string estadocivil { get; set; }
        public string idioma { get; set; }
        public string certificacion { get; set; }
        public string titulo { get; set; }
        public string ubicacion { get; set; }
    
        public virtual ICollection<PuestoPorExpediente> PuestoPorExpediente { get; set; }
    }
}
