//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public Perfiles()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int codPerfil { get; set; }
        public string nomperfil { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
