//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuestoPorExpediente
    {
        public int codpuesto { get; set; }
        public string identificacion { get; set; }
        public string titulo { get; set; }
        public string certificacion { get; set; }
        public string idioma { get; set; }
        public string aproboprueba { get; set; }
        public int promedioprueba { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
