//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuestoPorExpediente
    {
        public int codPuesto { get; set; }
        public string identificacion { get; set; }
        public string aproboprueba { get; set; }
        public Nullable<int> promedioprueba { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
