//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        public Puesto()
        {
            this.PuestoPorExpediente = new HashSet<PuestoPorExpediente>();
        }
    
        public int codpuesto { get; set; }
        public int disponibilidad { get; set; }
        public string nompuesto { get; set; }
    
        public virtual ICollection<PuestoPorExpediente> PuestoPorExpediente { get; set; }
    }
}
